Some changes in bash scripts
SixTrack/SixDesk pull request #48
Opened 2019-05-15 11:40 UTC by luxiaohan

1. Replace all the 'awk' commands with 'gawk'

2. Change some functions in dot_proflie and set_env.sh  to make syenv optional

3. Replace all the tabs with white-spaces

2019-05-20 08:45 UTC, amereghe requested changes
Hi Xiaohan,
many thanks for the work!

Some comments:
   * `awk` --> `gawk`: I saw that you also update the path to awk scripts: good move, thanks. Have you checked that no other `awk` statement was left behind?
   *  tabs: have you checked that no other tab char was left behind?

Have you run some tests? I guess you did, but just to be sure.

I had a further request by Frederik: could you add a `aklog` command anywhere you find `kinit`? The command should be placed right after and look like: `aklog -c cern.ch -k CERN.CH`
Following this change, the manual should be changed also, in Tab.~1.2, where we state the pre-requisites.

Thanks!

2019-05-20 11:30 UTC, luxiaohan commented
Hello Alessio,
     Yes, I checked with the command ```grep```. So I'm sure there aren't ```awk``` statement and tab char left behind, but just in the ```bash``` folder.
      Of course, I did some tests, submitted madx jobs  and sixtrack jobs to HTCondor, I didn't see any error. But I think you'd better do some tests as well for double check.
       And ok, I will add the statement for the new request asap, and I will update this pull request after the changes are done.
Thanks~

2019-05-20 12:10 UTC, amereghe commented
Hello Xiaohan,
ok, no worries, if you have run the tests, then it is fine with me.
Thanks for taking into account also the new request.

2019-05-24 14:25 UTC, amereghe requested changes
Thanks a lot, Xiaohan, for the work. I think that these modifications still need a bit of reworking. Thanks!

2019-05-24 14:25 UTC, amereghe commented on utilities/bash/control.sh
> +        aklog -c cern.ch -k CERN.CH
I would actually do something like:
   1. `kinit` (or `kinit -R`);
   1. check that `kinit` did not fail;
   1. `aklog`;
   1. check that `aklog` did not fail;
   1. `klist`

2019-05-24 14:25 UTC, amereghe commented on utilities/bash/dot_profile
> +    multipleTrials "kinit -R ; local __exit_status=\$?; aklog -c cern.ch -k CERN.CH" "[ \$__exit_status -eq 0 ]"
similarly to `control.sh`, I would keep `kinit` embedded in the `multipleTrials` algorithm, with the check of its success, and then have the `aklog` command, again as argument to the `multipleTrials` algorithm and a check afterwards

2019-05-24 14:25 UTC, amereghe commented on utilities/doc/chIntroduction.tex
> +    kerberos & to renew/check credentials via \texttt{klist}, \texttt{kinit} and \texttt{aklog} \\
I think `aklog` should be in the AFS line.
BTW: could you change:
`AFS (local mount)`
into:
`AFS (or openAFS for local mounting)`

Also:
`kerberos`
into:
`kerberos (local installation)`

2019-05-27 09:03 UTC, luxiaohan commented
Hi Alessio, 
   I have made the changes according to your comments!
Thanks~

2019-05-27 09:34 UTC, amereghe approved these changes

2019-05-27 11:49 UTC, merged